FROM node:18-alpine

WORKDIR app

COPY ["package.json", "/app"]

# This is run when the image is being created
RUN npm install

COPY . /app

EXPOSE 80

# This command adds an annonimous volume. In this case it will be used to prevent the node_modules of our application to be overwritten by a bind mount.
VOLUME ["/app/node_modules"]

# This is run when the container is started
CMD ["npm", "start"]

