FROM node:18-alpine

WORKDIR app

COPY ["package.json", "/app"]

# This is run when the image is being created
RUN npm install

COPY . /app

VOLUME ["/app/node_modules"]

# This is run when the container is started
CMD ["npm", "test"]

